# Name: Najia Khan (123)

# Lab-task-9

<div class ="alert alert-block alert-info">
     import <b> Libraries </b>
</div>

In [27]:
# libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder 
from sklearn.ensemble import RandomForestRegressor

<div class ="alert alert-block alert-success">
 <b>Data loading </b>
</div>

In [2]:
df = pd.read_csv("Dataset salary 2024.csv")
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,202730,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,92118,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,130500,US,0,US,M
3,2024,SE,FT,Data Engineer,96000,USD,96000,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
16529,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
16530,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
16531,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
16532,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
16533,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

<div class ="alert alert-block alert-success">
 <b>Data Expoloration </b>
</div>

In [3]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,202730,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,92118,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,130500,US,0,US,M
3,2024,SE,FT,Data Engineer,96000,USD,96000,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M

In [5]:
df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
16529,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
16530,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
16531,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
16532,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
16533,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [6]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16534 entries, 0 to 16533
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           16534 non-null  int64
 1   experience_level    16534 non-null  object
 2   employment_type     16534 non-null  object
 3   job_title           16534 non-null  object
 4   salary              16534 non-null  int64
 5   salary_currency     16534 non-null  object
 6   salary_in_usd       16534 non-null  int64
 7   employee_residence  16534 non-null  object
 8   remote_ratio        16534 non-null  int64
 9   company_location    16534 non-null  object
 10  company_size        16534 non-null  object
dtypes: int64(4), object(7)
memory usage: 1.4+ MB

In [8]:
df.shape

(16534, 11)

In [9]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  16534.000000  1.653400e+04   16534.000000  16534.000000
mean    2023.226866  1.637270e+05  149686.777973     32.003750
std        0.713558  3.402057e+05   68505.293156     46.245158
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2023.000000  1.017630e+05  101125.000000      0.000000
50%     2023.000000  1.422000e+05  141300.000000      0.000000
75%     2024.000000  1.872000e+05  185900.000000    100.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [10]:
df.count()

work_year             16534
experience_level      16534
employment_type       16534
job_title             16534
salary                16534
salary_currency       16534
salary_in_usd         16534
employee_residence    16534
remote_ratio          16534
company_location      16534
company_size          16534
dtype: int64

In [11]:
df["job_title"].unique()

array(['AI Engineer', 'Data Engineer', 'Machine Learning Engineer',
       'ML Engineer', 'Data Analyst', 'NLP Engineer', 'Data Scientist',
       'Applied Scientist', 'Data Manager', 'Data Architect',
       'Data Operations Manager', 'Research Scientist',
       'Data Science Manager', 'Business Intelligence Engineer',
       'Business Intelligence', 'Data Modeler',
       'Data Integration Specialist', 'Data Product Manager',
       'Data Visualization Specialist', 'Data Science', 'Data Specialist',
       'Business Intelligence Lead', 'Research Analyst',
       'Business Intelligence Analyst', 'AI Software Engineer',
       'Machine Learning Scientist', 'Data Science Engineer',
       'Machine Learning Operations Engineer', 'Analytics Engineer',
       'Data Management Analyst',
       'Encounter Data Management Professional',
       'Data Analytics Specialist', 'Head of Data', 'Data Analytics Lead',
       'Research Engineer', 'AI Scientist',
       'Business Intelligence Developer', 'Machine Learning Developer',
       'Data Management Specialist', 'Data Infrastructure Engineer',
       'BI Developer', 'Admin & Data Analyst', 'Insight Analyst',
       'Consultant Data Engineer', 'Business Intelligence Manager',
       'Manager Data Management', 'Data Quality Manager',
       'Data Analytics Manager', 'Robotics Engineer',
       'Business Intelligence Specialist', 'Data Operations Analyst',
       'Director of Business Intelligence', 'Data Product Owner',
       'AI Research Scientist', 'Data Operations Specialist',
       'Bear Robotics', 'Data Science Consultant', 'Data Lead',
       'Data Operations Associate', 'AI Architect', 'Lead Data Scientist',
       'MLOps Engineer', 'BI Analyst', 'Applied Research Scientist',
       'Prompt Engineer', 'Data Integration Engineer',
       'Machine Learning Infrastructure Engineer', 'Data Developer',
       'CRM Data Analyst', 'ETL Developer', 'Cloud Database Engineer',
       'Data Science Analyst', 'Data Science Practitioner',
       'BI Data Analyst', 'Applied Data Scientist',
       'Data Quality Engineer', 'Computational Biologist',
       'Big Data Engineer', 'Data Analytics Associate',
       'Data Reporting Analyst', 'Data Management Consultant',
       'Data Quality Analyst', 'Robotics Software Engineer',
       'Machine Learning Researcher', 'Data DevOps Engineer',
       'Data Science Director', 'Data Strategist', 'Big Data Developer',
       'Quantitative Research Analyst', 'Lead Machine Learning Engineer',
       'Machine Learning Research Engineer', 'Data Analytics Consultant',
       'AI Research Engineer', 'AI Programmer', 'ETL Engineer',
       'AI Product Manager', 'AI Developer', 'Computer Vision Engineer',
       'Head of Machine Learning', 'Data Analyst Lead',
       'Data Integration Developer', 'ML Ops Engineer',
       'Data Pipeline Engineer', 'Lead Data Analyst', 'Data Science Lead',
       'Director of Data Science', 'Managing Director Data Science',
       'Business Data Analyst', 'Marketing Data Scientist',
       'Deep Learning Engineer', 'Machine Learning Modeler',
       'Decision Scientist', 'Financial Data Analyst',
       'Data Strategy Manager', 'Data Visualization Engineer',
       'Azure Data Engineer', 'Principal Data Scientist',
       'Staff Data Analyst', 'Machine Learning Software Engineer',
       'Applied Machine Learning Scientist', 'Data Operations Engineer',
       'Machine Learning Manager', 'Principal Machine Learning Engineer',
       'Principal Data Engineer', 'Power BI Developer',
       'Head of Data Science', 'Staff Machine Learning Engineer',
       'Staff Data Scientist', 'Machine Learning Specialist',
       'Business Intelligence Data Analyst', 'Data Modeller',
       'Finance Data Analyst', 'Software Data Engineer',
       'Compliance Data Analyst', 'Cloud Data Engineer',
       'Analytics Engineering Manager', 'AWS Data Architect',
       'Product Data Analyst', 'Data Visualization Analyst',
       'Autonomous Vehicle Technician', 'Sales Data Analyst',
       'Applied Machine Learning Engineer', 'BI Data Engineer',
       'Deep Learning Researcher', 'Big Data Architect',
       'Computer Vision Software Engineer', 'Marketing Data Engineer',
       'Data Science Tech Lead', 'Data Scientist Lead',
       'Marketing Data Analyst', 'Principal Data Architect',
       'Data Analytics Engineer', 'Cloud Data Architect',
       'Lead Data Engineer', 'Principal Data Analyst'], dtype=object)

In [12]:
df.nunique()

work_year                5
experience_level         4
employment_type          4
job_title              155
salary                2560
salary_currency         23
salary_in_usd         2939
employee_residence      88
remote_ratio             3
company_location        77
company_size             3
dtype: int64

In [13]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

# Lab-Task-10

<div class ="alert alert-block alert-success">
 <b>Data Pre-Proceesing </b>
</div>

<div class ="alert alert-block alert-warning">
 <b>Manage Null-values </b>
</div>

In [16]:
df.drop("salary_in_usd",axis=1,inplace=True)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,US,0,US,M
3,2024,SE,FT,Data Engineer,96000,USD,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,190000,USD,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...
16529,2020,SE,FT,Data Scientist,412000,USD,US,100,US,L
16530,2021,MI,FT,Principal Data Scientist,151000,USD,US,100,US,L
16531,2020,EN,FT,Data Scientist,105000,USD,US,100,US,S
16532,2020,EN,CT,Business Data Analyst,100000,USD,US,100,US,L
16533,2021,SE,FT,Data Science Manager,7000000,INR,IN,50,IN,L

In [14]:
df['salary_currency'] =df['salary_currency'].fillna(df['salary_currency'].mode()[0])

In [15]:
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,202730,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,92118,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,130500,US,0,US,M
3,2024,SE,FT,Data Engineer,96000,USD,96000,US,0,US,M
4,2024,SE,FT,Machine Learning Engineer,190000,USD,190000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
16529,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
16530,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
16531,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
16532,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
16533,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [16]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

<div class ="alert alert-block alert-warning">
 <b>Manage Data Types </b>
</div>

## Changing Datatypes of Columns to be "Int"

In [17]:
def changefloattypes(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns_to_int = ['work_year', 'salary', 'remote_ratio']
changefloattypes(columns_to_int)

In [18]:
def changeonstringintoInt(cols):
    for i in cols:
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(df[i]))
        df[i] = data_LE.transform(df[i])

columns = ['experience_level', 'employment_type', 'job_title',
            'salary_currency', 'employee_residence',
            'company_location', 'company_size']

changeonstringintoInt(columns)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16534 entries, 0 to 16533
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           16534 non-null  int64
 1   experience_level    16534 non-null  int64
 2   employment_type     16534 non-null  int64
 3   job_title           16534 non-null  int64
 4   salary              16534 non-null  int64
 5   salary_currency     16534 non-null  int64
 6   salary_in_usd       16534 non-null  int64
 7   employee_residence  16534 non-null  int64
 8   remote_ratio        16534 non-null  int64
 9   company_location    16534 non-null  int64
 10  company_size        16534 non-null  int64
dtypes: int64(11)
memory usage: 1.4 MB

# Lab-task-11

<div class ="alert alert-block alert-success">
 <b> Train-Test splitting </b>
</div>

In [33]:
X=df.drop("salary", axis=1)
Y=df['salary']

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)

<div class ="alert alert-block alert-warning">
 <b> Applying Model </b>
</div>

In [36]:


model = RandomForestRegressor()
model.fit(X_train, Y_train)

RandomForestRegressor()

In [37]:
Y_pred = model.predict(X_test)

<div class ="alert alert-block alert-warning">
 <b> Accuracy </b>
</div>

In [41]:
from sklearn.metrics import r2_score

acc = r2_score(Y_test, Y_pred)
print("Accuracy:", acc)

Accuracy: 0.6953094042097466